# Test HKJC Football DataProvider

## 0. Import Packages

In [1]:
# Import Libraries
## Standard Libraries
import datetime
import json
import logging
import os
import sys

## Third-Party Libraries
import pandas as pd

## Local Libraries
sys.path.append("D:\\workspace\\hkjc_football")
from hkjc_core.data.data_provider import HKJC_Football_DataProvider

In [2]:
hkjc_fb_dp = HKJC_Football_DataProvider(
    instance_id=42,
    log_level=logging.DEBUG,
    base_url="https://info.cld.hkjc.com/graphql/base/",
    max_retries=3,
    retry_backoff_factor=0.3,
)

## 1. Test Query for Team IDs

In [3]:
team_id_dict = hkjc_fb_dp.get_team_ids()
team_info_df = pd.DataFrame(team_id_dict["data"]["teamList"])
print(len(team_info_df))
team_info_df.head()

5414

         id code  name_ch               name_en
0  50000001  TMN  1860慕尼黑           1860 Munich
1  50430573  WBA  3B亞馬遜女足  3B da Amazonia Women
2  50000002  OCT     十月九日          9 de Octubre
3  50000003  AAS    澳職明星隊    A-League All Stars
4  50000004  AAG       真特               AA Gent

In [5]:
team_id_dict

{'data': {'teamList': [{'id': '50000001',
    'code': 'TMN',
    'name_ch': '1860慕尼黑',
    'name_en': '1860 Munich'},
   {'id': '50430573',
    'code': 'WBA',
    'name_ch': '3B亞馬遜女足',
    'name_en': '3B da Amazonia Women'},
   {'id': '50000002',
    'code': 'OCT',
    'name_ch': '十月九日',
    'name_en': '9 de Octubre'},
   {'id': '50000003',
    'code': 'AAS',
    'name_ch': '澳職明星隊',
    'name_en': 'A-League All Stars'},
   {'id': '50000004', 'code': 'AAG', 'name_ch': '真特', 'name_en': 'AA Gent'},
   {'id': '50362134',
    'code': 'GTW',
    'name_ch': '真特女足',
    'name_en': 'AA Gent Women'},
   {'id': '50000005',
    'code': 'ABC',
    'name_ch': 'ABC納泰',
    'name_en': 'ABC Natal'},
   {'id': '50000006',
    'code': 'ACA',
    'name_ch': '阿些斯奧',
    'name_en': 'AC Ajaccio'},
   {'id': '50000007',
    'code': 'AES',
    'name_ch': '艾米恩斯體育會',
    'name_en': 'AC Amiens'},
   {'id': '50586741',
    'code': 'AIR',
    'name_ch': 'AC卡連拿',
    'name_en': 'AC Carina'},
   {'id': '50000008', 'code': 'ACM', 'name_ch': 'AC米蘭', 'name_en': 'AC Milan'},
   {'id': '50355625',
    'code': 'AWC',
    'name_ch': 'AC米蘭女足',
    'name_en': 'AC Milan Women'},
   {'id': '50000009',
    'code': 'U13',
    'name_ch': 'AC-尼科西亞',
    'name_en': 'AC Milan-APOEL'},
   {'id': '50324165',
    'code': 'R94',
    'name_ch': 'AC米蘭-阿特蘭大',
    'name_en': 'AC Milan-Atalanta'},
   {'id': '50324164',
    'code': 'R93',
    'name_ch': 'AC米蘭-賓菲加',
    'name_en': 'AC Milan-Benfica'},
   {'id': '50000010',
    'code': 'U12',
    'name_ch': 'AC米蘭-馬賽',
    'name_en': 'AC Milan-Marseille'},
   {'id': '50240301', 'code': 'AUU', 'name_ch': 'AC奧盧', 'name_en': 'AC Oulu'},
   {'id': '50000011',
    'code': 'ACS',
    'name_ch': '聖路爾斯',
    'name_en': 'AC St. Louis'},
   {'id': '50600009',
    'code': 'SNA',
    'name_ch': 'AC史杜丹達拿',
    'name_en': 'AC Studenterna'},
   {'id': '50000012', 'code': 'ACT', 'name_ch': '拖連奴', 'name_en': 'AC Torino'},
   {'id': '50557337',
    'code': 'AVM',
    'name_ch': 'AC維拉米亞',
    'name_en': 'AC Vila Mea'},
   {'id': '50331715',
    'code': 'VIA',
    'name_ch': 'AC維圖斯',
    'name_en': 'AC Virtus'},
   {'id': '50560154', 'code': 'FAF', 'name_ch': '法菲', 'name_en': 'AD Fafe'},
   {'id': '50267253',
    'code': 'MAD',
    'name_ch': 'AD梅里達',
    'name_en': 'AD Merida'},
   {'id': '50000013',
    'code': 'SCL',
    'name_ch': 'AD聖卡洛斯',
    'name_en': 'AD San Carlos'},
   {'id': '50319123',
    'code': 'ADT',
    'name_ch': 'ADT塔爾馬',
    'name_en': 'ADT Tarma'},
   {'id': '50000014',
    'code': 'AEK',
    'name_ch': 'AEK雅典',
    'name_en': 'AEK Athens'},
   {'id': '50462448',
    'code': 'WAE',
    'name_ch': 'AEK雅典女足',
    'name_en': 'AEK Athens Women'},
   {'id': '50000015',
    'code': 'LAR',
    'name_ch': 'AEK拉亞拿卡',
    'name_en': 'AEK Larnaca'},
   {'id': '50000016',
    'code': 'AEL',
    'name_ch': 'AEL利馬素',
    'name_en': 'AEL Limassol'},
   {'id': '50266845',
    'code': 'AFO',
    'name_ch': 'AF維洛斯',
    'name_en': 'AF Virois'},
   {'id': '50000017',
    'code': 'AFU',
    'name_ch': '艾斯基斯杜拿',
    'name_en': 'AFC Eskilstuna'},
   {'id': '50000018',
    'code': 'FYD',
    'name_ch': 'AFC費迪',
    'name_en': 'AFC Fylde'},
   {'id': '50000019',
    'code': 'TEL',
    'name_ch': 'AFC特爾福德',
    'name_en': 'AFC Telford'},
   {'id': '50000020', 'code': 'TTT', 'name_ch': '托頓', 'name_en': 'AFC Totton'},
   {'id': '50000021',
    'code': 'TBZ',
    'name_ch': 'AFC圖比斯',
    'name_en': 'AFC Tubize'},
   {'id': '50000022',
    'code': 'AWB',
    'name_ch': 'AFC 溫布頓',
    'name_en': 'AFC Wimbledon'},
   {'id': '50000023',
    'code': 'AGF',
    'name_ch': '阿侯斯',
    'name_en': 'AGF Aarhus'},
   {'id': '50000024',
    'code': 'AGM',
    'name_ch': 'AGMK足球會',
    'name_en': 'AGMK FC'},
   {'id': '50000025',
    'code': 'AGV',
    'name_ch': '阿高夫',
    'name_en': 'AGOVV Apeldoorn'},
   {'id': '156', 'code': 'AIK', 'name_ch': 'AIK', 'name_en': 'AIK'},
   {'id': '50000026',
    'code': 'ASA',
    'name_ch': 'AIK蘇納',
    'name_en': 'AIK Solna'},
   {'id': '50353898',
    'code': 'AKW',
    'name_ch': 'AIK蘇納女足',
    'name_en': 'AIK Solna Women'},
   {'id': '50544237',
    'code': 'APW',
    'name_ch': 'APF FC女足',
    'name_en': 'APF FC Women'},
   {'id': '50000027',
    'code': 'LHT',
    'name_ch': '萊卡特',
    'name_en': 'APIA Leichhardt'},
   {'id': '50000028', 'code': 'APO', 'name_ch': '尼科西亞', 'name_en': 'APOEL'},
   {'id': '50000029',
    'code': 'ASB',
    'name_ch': '博韋',
    'name_en': 'AS Beauvais'},
   {'id': '50000030',
    'code': 'ABZ',
    'name_ch': '比斯亞斯',
    'name_en': 'AS Beziers'},
   {'id': '50000031',
    'code': 'ASM',
    'name_ch': '明古迪斯',
    'name_en': 'AS Minguettes'},
   {'id': '50000032', 'code': 'APR', 'name_ch': '皮萊', 'name_en': 'AS Pirae'},
   {'id': '50000033',
    'code': 'TCN',
    'name_ch': '特倫辛',
    'name_en': 'AS Trencin'},
   {'id': '50000034',
    'code': 'ASP',
    'name_ch': '阿拉比拉卡',
    'name_en': 'ASA Arapiraca'},
   {'id': '50555605',
    'code': 'ABM',
    'name_ch': '比斯海姆',
    'name_en': 'ASC Biesheim'},
   {'id': '50000035',
    'code': 'ADZ',
    'name_ch': '安德列斯奧斯',
    'name_en': 'ASF Andrezieux'},
   {'id': '50000036',
    'code': 'BLF',
    'name_ch': 'ASM貝爾福',
    'name_en': 'ASM Belfort'},
   {'id': '50000037',
    'code': 'GEL',
    'name_ch': 'ASV加爾',
    'name_en': 'ASV Geel'},
   {'id': '50000038',
    'code': 'ATG',
    'name_ch': '格拉曼尼',
    'name_en': 'AT Gramanet'},
   {'id': '50260993', 'code': 'VFQ', 'name_ch': 'AVS', 'name_en': 'AVS'},
   {'id': '50000039',
    'code': 'AZZ',
    'name_ch': '阿爾克馬爾',
    'name_en': 'AZ Alkmaar'},
   {'id': '50362115',
    'code': 'AWZ',
    'name_ch': '阿爾克馬爾女足',
    'name_en': 'AZ Alkmaar Women'},
   {'id': '50000040', 'code': 'AAC', 'name_ch': '亞琛', 'name_en': 'Aachen'},
   {'id': '50000041',
    'code': 'AII',
    'name_ch': '亞琛二隊',
    'name_en': 'Aachen II'},
   {'id': '50000042', 'code': 'AAL', 'name_ch': '阿爾堡', 'name_en': 'Aalborg'},
   {'id': '50000043', 'code': 'AAE', 'name_ch': '阿里辛特', 'name_en': 'Aalesund'},
   {'id': '50566599',
    'code': 'WSA',
    'name_ch': '阿里辛特女足',
    'name_en': 'Aalesund Women'},
   {'id': '50000044', 'code': 'ABE', 'name_ch': '鴨巴甸', 'name_en': 'Aberdeen'},
   {'id': '50356316',
    'code': 'AFW',
    'name_ch': '鴨巴甸女足',
    'name_en': 'Aberdeen Women'},
   {'id': '50000045',
    'code': 'ABY',
    'name_ch': '艾伯里斯特夫',
    'name_en': 'Aberystwyth Town'},
   {'id': '50357018', 'code': 'AHF', 'name_ch': '艾伯哈FC', 'name_en': 'Abha FC'},
   {'id': '50000046',
    'code': 'ART',
    'name_ch': '艾巴蘭迪斯',
    'name_en': 'Abrantes'},
   {'id': '50000047',
    'code': 'APC',
    'name_ch': '卡貝略港大學',
    'name_en': 'Academia Puerto Cabello'},
   {'id': '50000048',
    'code': 'ACC',
    'name_ch': '科英布拉大學',
    'name_en': 'Academica Coimbra'},
   {'id': '50585202', 'code': 'USS', 'name_ch': '阿卡蘇索', 'name_en': 'Acassuso'},
   {'id': '50000049',
    'code': 'ACR',
    'name_ch': '阿克寧頓',
    'name_en': 'Accrington Stanley'},
   {'id': '50000050', 'code': 'AHS', 'name_ch': '阿基里斯', 'name_en': 'Achilles'},
   {'id': '50000051', 'code': 'ACH', 'name_ch': '艾治拿斯', 'name_en': 'Achnas'},
   {'id': '50289780',
    'code': 'ADS',
    'name_ch': '阿達納鐵路',
    'name_en': 'Adana Demirspor'},
   {'id': '50000052',
    'code': 'ADD',
    'name_ch': '阿德萊德城',
    'name_en': 'Adelaide City'},
   {'id': '50599269',
    'code': 'ACB',
    'name_ch': '阿德萊德眼鏡蛇',
    'name_en': 'Adelaide Cobras'},
   {'id': '50476345',
    'code': 'ATR',
    'name_ch': '阿德萊德突擊者',
    'name_en': 'Adelaide Croatia Raiders'},
   {'id': '50000053',
    'code': 'AOY',
    'name_ch': '阿德萊德奧林匹克',
    'name_en': 'Adelaide Olympic'},
   {'id': '50000054',
    'code': 'ADL',
    'name_ch': '阿德萊德聯',
    'name_en': 'Adelaide Utd'},
   {'id': '50377155',
    'code': 'WAU',
    'name_ch': '阿德萊德聯女足',
    'name_en': 'Adelaide Utd Women'},
   {'id': '50000055',
    'code': 'ADW',
    'name_ch': '艾特米拿',
    'name_en': 'Admira Wacker'},
   {'id': '50000056',
    'code': 'AFG',
    'name_ch': '阿富汗',
    'name_en': 'Afghanistan'},
   {'id': '50000057',
    'code': 'AF4',
    'name_ch': '阿富汗男亞足',
    'name_en': 'Afghanistan AM'},
   {'id': '50332396',
    'code': 'AF2',
    'name_ch': '阿富汗U20',
    'name_en': 'Afghanistan U20'},
   {'id': '50302158',
    'code': 'AF3',
    'name_ch': '阿富汗U23',
    'name_en': 'Afghanistan U23'},
   {'id': '50000058', 'code': 'W14', 'name_ch': '非洲', 'name_en': 'Africa'},
   {'id': '50000059', 'code': 'AGD', 'name_ch': '阿格德', 'name_en': 'Agde'},
   {'id': '50000060', 'code': 'AGE', 'name_ch': '艾根', 'name_en': 'Agen'},
   {'id': '50462430',
    'code': 'WGR',
    'name_ch': '阿格拉姆女足',
    'name_en': 'Agram Women'},
   {'id': '50000061',
    'code': 'APU',
    'name_ch': '阿高比古里奧',
    'name_en': 'Agropecuario'},
   {'id': '50000062',
    'code': 'AAT',
    'name_ch': '阿古亞辛達',
    'name_en': 'Agua Santa'},
   {'id': '50282104',
    'code': 'ADM',
    'name_ch': '阿古亞馬拉巴',
    'name_en': 'Aguia de Maraba'},
   {'id': '50002636',
    'code': 'IGI',
    'name_ch': '阿古拿斯',
    'name_en': 'Aguilas Doradas'},
   {'id': '50308218',
    'code': 'AUI',
    'name_ch': '阿古拉斯FC',
    'name_en': 'Aguilas FC'},
   {'id': '50000063', 'code': 'AFK', 'name_ch': '阿哈爾', 'name_en': 'Ahal FK'},
   {'id': '50000064', 'code': 'AHL', 'name_ch': '艾倫', 'name_en': 'Ahlen'},
   {'id': '50000065',
    'code': 'AFR',
    'name_ch': '空軍體育會',
    'name_en': 'Air Force AC'},
   {'id': '50000066',
    'code': 'AIU',
    'name_ch': '艾迪爾聯',
    'name_en': 'Airdrieonians'},
   {'id': '50000067',
    'code': 'FAZ',
    'name_ch': 'FC艾查威爾',
    'name_en': 'Aizawl FC'},
   {'id': '50000068', 'code': 'AJX', 'name_ch': '阿積士', 'name_en': 'Ajax'},
   {'id': '50000069',
    'code': 'AAM',
    'name_ch': '阿積士業餘隊',
    'name_en': 'Ajax Amateure'},
   {'id': '50000070',
    'code': 'AXC',
    'name_ch': '阿積士開普敦',
    'name_en': 'Ajax Cape Town'},
   {'id': '50362114',
    'code': 'AXW',
    'name_ch': '阿積士女足',
    'name_en': 'Ajax Women'},
   {'id': '50000071',
    'code': 'R56',
    'name_ch': '阿積士-巴塞',
    'name_en': 'Ajax-Barcelona'},
   {'id': '50000072',
    'code': 'R58',
    'name_ch': '阿積士-祖雲達斯',
    'name_en': 'Ajax-Juventus'},
   {'id': '50000073',
    'code': 'R57',
    'name_ch': '阿積士-利物浦',
    'name_en': 'Ajax-Liverpool'},
   {'id': '50000074',
    'code': 'R55',
    'name_ch': '阿積士-曼城',
    'name_en': 'Ajax-Manchester City'},
   {'id': '50000075',
    'code': 'R59',
    'name_ch': '阿積士-曼聯',
    'name_en': 'Ajax-Manchester Utd'},
   {'id': '50000076',
    'code': 'R41',
    'name_ch': '阿積士-波圖',
    'name_en': 'Ajax-Porto'},
   {'id': '50000077',
    'code': 'R60',
    'name_ch': '阿積士-熱刺',
    'name_en': 'Ajax-Tottenham'},
   {'id': '50482781',
    'code': 'AJM',
    'name_ch': '阿吉曼會',
    'name_en': 'Ajman Club'},
   {'id': '50000078',
    'code': 'APD',
    'name_ch': '彭迪夫學院',
    'name_en': 'Akademija Pandev'},
   {'id': '2260',
    'code': 'AKH',
    'name_ch': '阿卡沙',
    'name_en': 'Akhisar Belediyespor'},
   {'id': '50000079',
    'code': 'AKS',
    'name_ch': '阿卡沙',
    'name_en': 'Akhisarspor'},
   {'id': '50000080',
    'code': 'TGY',
    'name_ch': '艾卡馬特',
    'name_en': 'Akhmat Grozny'},
   {'id': '50272543',
    'code': 'AKY',
    'name_ch': '阿克隆陶爾亞蒂',
    'name_en': 'Akron Tolyatti'},
   {'id': '50000081', 'code': 'AKB', 'name_ch': '阿克圖比', 'name_en': 'Aktobe'},
   {'id': '50462456',
    'code': 'WAK',
    'name_ch': '阿克圖比女足',
    'name_en': 'Aktobe Women'},
   {'id': '50357012',
    'code': 'ADH',
    'name_ch': '艾阿達拉',
    'name_en': 'Al Adalah'},
   {'id': '50000082', 'code': 'AHI', 'name_ch': '阿爾阿里', 'name_en': 'Al Ahli'},
   {'id': '50334370',
    'code': 'AAH',
    'name_ch': '多哈艾阿里',
    'name_en': 'Al Ahli Doha'},
   {'id': '50000083',
    'code': 'AAJ',
    'name_ch': '吉達艾阿里',
    'name_en': 'Al Ahli Jeddah'},
   {'id': '50334363',
    'code': 'AHM',
    'name_ch': '艾阿里麥納麥',
    'name_en': 'Al Ahli Manama'},
   {'id': '50000084', 'code': 'AIA', 'name_ch': '艾阿里', 'name_en': 'Al Ahly'},
   {'id': '50000085', 'code': 'AIN', 'name_ch': '艾阿恩', 'name_en': 'Al Ain'},
   {'id': '50357016',
    'code': 'AIS',
    'name_ch': '沙特艾阿恩',
    'name_en': 'Al Ain Saudi'},
   {'id': '50000086',
    'code': 'AAD',
    'name_ch': '多哈艾阿拉比',
    'name_en': 'Al Arabi Doha'},
   {'id': '50357008',
    'code': 'AZR',
    'name_ch': '歐奈宰艾阿拉比',
    'name_en': 'Al Arabi Unaizah'},
   {'id': '50482780', 'code': 'ABH', 'name_ch': '艾巴塔', 'name_en': 'Al Bataeh'},
   {'id': '50357009', 'code': 'ABT', 'name_ch': '艾巴騰', 'name_en': 'Al Batin'},
   {'id': '50538600', 'code': 'ABD', 'name_ch': '艾比達', 'name_en': 'Al Bidda'},
   {'id': '50357014',
    'code': 'ABK',
    'name_ch': '艾布基里耶',
    'name_en': 'Al Bukiryah'},
   {'id': '50482783',
    'code': 'ADF',
    'name_ch': '艾迪哈夫拉',
    'name_en': 'Al Dhafra'},
   {'id': '50000087',
    'code': 'LKH1',
    'name_ch': '艾杜哈尼',
    'name_en': 'Al Duhail'},
   {'id': '50000088',
    'code': 'AEQ',
    'name_ch': '伊蒂法克',
    'name_en': 'Al Ettifaq'},
   {'id': '50000089',
    'code': 'FAM',
    'name_ch': '艾費薩里安曼',
    'name_en': 'Al Faisaly Amman'},
   {'id': '50000090',
    'code': 'AFS',
    'name_ch': '費薩里FC',
    'name_en': 'Al Faisaly FC'},
   {'id': '50000091', 'code': 'ALF', 'name_ch': '艾法特', 'name_en': 'Al Fateh'},
   {'id': '50289793', 'code': 'AFH', 'name_ch': '艾費哈', 'name_en': 'Al Fayha'},
   {'id': '50000092',
    'code': 'ARF',
    'name_ch': '艾加拉法',
    'name_en': 'Al Gharafa'},
   {'id': '50357011', 'code': 'AHZ', 'name_ch': '艾哈森', 'name_en': 'Al Hazem'},
   {'id': '50000093', 'code': 'ALH', 'name_ch': '艾希迪', 'name_en': 'Al Hidd'},
   {'id': '50000094', 'code': 'HLL', 'name_ch': '希拉爾', 'name_en': 'Al Hilal'},
   {'id': '50472625',
    'code': 'Q99',
    'name_ch': '希拉爾-國際邁亞密',
    'name_en': 'Al Hilal-Inter Miami CF'},
   {'id': '50472626',
    'code': 'O46',
    'name_ch': '希拉爾-蒙特雷',
    'name_en': 'Al Hilal-Monterrey'},
   {'id': '50334359',
    'code': 'AIB',
    'name_ch': '艾侯賽因伊比',
    'name_en': 'Al Hussein Irbid'},
   {'id': '50000095',
    'code': 'AIT',
    'name_ch': '伊蒂哈德',
    'name_en': 'Al Ittihad'},
   {'id': '50357015',
    'code': 'AJL',
    'name_ch': '艾查巴萊',
    'name_en': 'Al Jabalain'},
   {'id': '50000096',
    'code': 'AJS',
    'name_ch': '艾查殊SC',
    'name_en': 'Al Jaish SC'},
   {'id': '50357013',
    'code': 'AJD',
    'name_ch': '艾真達爾',
    'name_en': 'Al Jandal'},
   {'id': '50000097',
    'code': 'AJA',
    'name_ch': '艾查捷拉',
    'name_en': 'Al Jazira'},
   {'id': '50536403',
    'code': 'ALJ',
    'name_ch': '艾朱拜勒',
    'name_en': 'Al Jubail'},
   {'id': '50000098',
    'code': 'KRM',
    'name_ch': '卡拉馬',
    'name_en': 'Al Karamah'},
   {'id': '50334361',
    'code': 'AKD',
    'name_ch': '艾卡列迪亞',
    'name_en': 'Al Khaldiya'},
   {'id': '50334373',
    'code': 'AKJ',
    'name_ch': '卡赫利',
    'name_en': 'Al Khaleej'},
   {'id': '50456853',
    'code': 'AAY',
    'name_ch': '艾卡列迪耶夫',
    'name_en': 'Al Kharaitiyat'},
   {'id': '50334374',
    'code': 'AOO',
    'name_ch': '艾科魯特',
    'name_en': 'Al Kholood'},
   {'id': '50334371', 'code': 'AKH', 'name_ch': '艾科爾', 'name_en': 'Al Khor'},
   {'id': '50538601',
    'code': 'AMK',
    'name_ch': '艾馬希亞',
    'name_en': 'Al Markhiya'},
   {'id': '50462423',
    'code': 'ARQ',
    'name_ch': '艾慕哈瑞克',
    'name_en': 'Al Muharraq'},
   {'id': '50000099', 'code': 'ANH', 'name_ch': '艾拿達', 'name_en': 'Al Nahda'},
   {'id': '50357017', 'code': 'ANJ', 'name_ch': '艾拿積馬', 'name_en': 'Al Najma'},
   {'id': '50000100',
    'code': 'ANS',
    'name_ch': '阿爾納沙',
    'name_en': 'Al Nasr SC'},
   {'id': '50000101', 'code': 'ANR', 'name_ch': '艾納斯', 'name_en': 'Al Nassr'},
   {'id': '50544242',
    'code': 'NWA',
    'name_ch': '艾納斯女足',
    'name_en': 'Al Nassr Women'},
   {'id': '50334375',
    'code': 'AOD',
    'name_ch': '艾科多',
    'name_en': 'Al Okhdood'},
   {'id': '50334376',
    'code': 'AOH',
    'name_ch': '艾奧魯巴',
    'name_en': 'Al Orobah'},
   {'id': '50000102',
    'code': 'AQS',
    'name_ch': '艾卡迪斯亞',
    'name_en': 'Al Qadsia'},
   {'id': '50334377',
    'code': 'AQA',
    'name_ch': '艾卡迪沙',
    'name_en': 'Al Qadsiah'},
   {'id': '50334378', 'code': 'ARB', 'name_ch': '艾拉德', 'name_en': 'Al Raed'},
   {'id': '50000103', 'code': 'ARN', 'name_ch': '艾雷恩', 'name_en': 'Al Rayyan'},
   {'id': '50000104', 'code': 'AFF', 'name_ch': '阿爾列法', 'name_en': 'Al Riffa'},
   {'id': '50334379',
    'code': 'RYH',
    'name_ch': '艾利雅德',
    'name_en': 'Al Riyadh'},
   {'id': '50000105', 'code': 'ASD', 'name_ch': '艾薩德', 'name_en': 'Al Sadd'},
   {'id': '50357020', 'code': 'ASF', 'name_ch': '艾沙法', 'name_en': 'Al Safa'},
   {'id': '50000106',
    'code': 'ASL',
    'name_ch': '艾塞利亞',
    'name_en': 'Al Sailiya'},
   {'id': '50289798', 'code': 'AEB', 'name_ch': '艾席貝', 'name_en': 'Al Seeb'},
   {'id': '50000107', 'code': 'ASH', 'name_ch': '艾沙比', 'name_en': 'Al Shabab'},
   {'id': '50000108',
    'code': 'ABB',
    'name_ch': '艾沙比阿拉比',
    'name_en': 'Al Shabab Al Arabi'},
   {'id': '50334372',
    'code': 'AHH',
    'name_ch': '艾沙哈尼亞',
    'name_en': 'Al Shahania'},
   {'id': '50334369', 'code': 'AHA', 'name_ch': '艾沙瑪', 'name_en': 'Al Shamal'},
   {'id': '50000109',
    'code': 'AHR',
    'name_ch': 'SC艾索達',
    'name_en': 'Al Shorta SC'},
   {'id': '50000110',
    'code': 'ATW',
    'name_ch': '艾塔亞文',
    'name_en': 'Al Taawoun'},
   {'id': '50357010', 'code': 'TAI', 'name_ch': '艾泰爾', 'name_en': 'Al Tai'},
   {'id': '50538602', 'code': 'WAB', 'name_ch': '艾華比', 'name_en': 'Al Waab'},
   {'id': '50000111', 'code': 'AWD', 'name_ch': '阿爾華達', 'name_en': 'Al Wahda'},
   {'id': '50289795',
    'code': 'AWK',
    'name_ch': '艾華卡拉',
    'name_en': 'Al Wakrah'},
   {'id': '50000112', 'code': 'AWS', 'name_ch': '艾華斯爾', 'name_en': 'Al Wasl'},
   {'id': '50000113', 'code': 'AWA', 'name_ch': '艾維達', 'name_en': 'Al Wehda'},
   {'id': '50000114', 'code': 'AWH', 'name_ch': '艾華達', 'name_en': 'Al Wehdat'},
   {'id': '50000115',
    'code': 'AZW',
    'name_ch': '艾祖拉',
    'name_en': "Al Zawra'a"},
   {'id': '50540589', 'code': 'AZI', 'name_ch': '艾祖爾菲', 'name_en': 'Al Zulfi'},
   {'id': '50000116',
    'code': 'AJU',
    'name_ch': '阿拉祖蘭斯',
    'name_en': 'Alajuelense'},
   {'id': '50000117',
    'code': 'AVK',
    'name_ch': '阿蘭尼亞',
    'name_en': 'Alania Vladikavkaz'},
   {'id': '50000118',
    'code': 'AYP',
    'name_ch': '艾蘭亞',
    'name_en': 'Alanyaspor'},
   {'id': '50000119',
    'code': 'ALK',
    'name_ch': '艾拉斯克特',
    'name_en': 'Alashkert'},
   {'id': '50000120', 'code': 'ALS', 'name_ch': '艾拉維斯', 'name_en': 'Alaves'},
   {'id': '50600414',
    'code': 'ALAW',
    'name_ch': '艾拉維斯女足',
    'name_en': 'Alaves Women'},
   {'id': '50000121',
    'code': 'ALB',
    'name_ch': '阿爾巴塞特',
    'name_en': 'Albacete'},
   {'id': '50000122', 'code': 'ALA', 'name_ch': '阿爾巴尼亞', 'name_en': 'Albania'},
   {'id': '50000123',
    'code': 'ALY',
    'name_ch': '阿爾巴尼亞U21',
    'name_en': 'Albania U21'},
   {'id': '50303164',
    'code': 'ALW',
    'name_ch': '阿爾巴尼亞女足',
    'name_en': 'Albania Women'},
   {'id': '50362147',
    'code': 'WAG',
    'name_ch': '艾伯加里亞女足',
    'name_en': 'Albergaria Women'},
   {'id': '50000124', 'code': 'ALI', 'name_ch': '阿爾比', 'name_en': 'Albi'},
   {'id': '50000125',
    'code': 'ABF',
    'name_ch': '艾賓奴列夫',
    'name_en': 'Albinoleffe'},
   {'id': '50562874',
    'code': 'ANF',
    'name_ch': '艾比安FC',
    'name_en': 'Albion FC'},
   {'id': '50000126',
    'code': 'ABR',
    'name_ch': '艾比安流浪',
    'name_en': 'Albion Rovers'},
   {'id': '50000127',
    'code': 'ALR',
    'name_ch': '新潟天鵝',
    'name_en': 'Albirex Niigata'},
   {'id': '50355585',
    'code': 'AWN',
    'name_ch': '新潟天鵝女足',
    'name_en': 'Albirex Niigata Women'},
   {'id': '50000128', 'code': 'AON', 'name_ch': '艾高干', 'name_en': 'Alcorcon'},
   {'id': '50000129', 'code': 'ACY', 'name_ch': '艾高恩奴', 'name_en': 'Alcoyano'},
   {'id': '50000130',
    'code': 'ALD',
    'name_ch': '艾迪索特',
    'name_en': 'Aldershot'},
   {'id': '50000131', 'code': 'AVI', 'name_ch': '阿度斯維', 'name_en': 'Aldosivi'},

In [4]:
team_info_df.loc[team_info_df["name_en"] == "Real Madrid"]

            id code name_ch      name_en
4120  50002589  RMD   皇家馬德里  Real Madrid

In [25]:
team_info_df.to_csv("D:\\workspace\\hkjc_football\\sample_data\\team_data\\team_infos_table.csv", index=False)

## 2. Test Query for Historical Matches

In [6]:
match_records_list = hkjc_fb_dp.get_historical_matches(
    start_date=datetime.date(2026, 1, 1),
    end_date=datetime.date(2026, 6, 12),
    team_id="50002589",
)

In [7]:
len(match_records_list)

31

In [8]:
match_records_list[0]

{'id': '50060631',
 'status': 'MATCHENDED',
 'frontEndId': 'FB2757',
 'matchDayOfWeek': '',
 'matchNumber': '',
 'matchDate': '2026-01-29+08:00',
 'kickOffTime': '2026-01-29T04:00:00.000+08:00',
 'sequence': '1.1769630400.11.UE Champions                                                                                                                    .1.08.Benfica                                                                                                                         .000',
 'homeTeam': {'id': '50000449', 'name_en': 'Benfica', 'name_ch': '賓菲加'},
 'awayTeam': {'id': '50002589', 'name_en': 'Real Madrid', 'name_ch': '皇家馬德里'},
 'tournament': {'code': 'UCL',
  'name_en': 'UE Champions',
  'name_ch': '歐洲聯賽冠軍盃'},
 'results': [{'homeResult': 0,
   'awayResult': 1,
   'resultConfirmType': 5,
   'payoutConfirmed': True,
   'stageId': 2,
   'resultType': 1,
   'sequence': 45},
  {'homeResult': 1,
   'awayResult': 1,
   'resultConfirmType': 5,
   'payoutConfirmed': True,
   'stageId': 2,
   'resultType': 1,
   'sequence': 46},
  {'homeResult': 2,
   'awayResult': 1,
   'resultConfirmType': 2,
   'payoutConfirmed': True,
   'stageId': 2,
   'resultType': 1,
   'sequence': 47},
  {'homeResult': 2,
   'awayResult': 1,
   'resultConfirmType': 2,
   'payoutConfirmed': True,
   'stageId': 3,
   'resultType': 1,
   'sequence': 48},
  {'homeResult': 3,
   'awayResult': 1,
   'resultConfirmType': 2,
   'payoutConfirmed': True,
   'stageId': 4,
   'resultType': 1,
   'sequence': 49},
  {'homeResult': 3,
   'awayResult': 2,
   'resultConfirmType': 2,
   'payoutConfirmed': True,
   'stageId': 4,
   'resultType': 1,
   'sequence': 50},
  {'homeResult': 4,
   'awayResult': 2,
   'resultConfirmType': 2,
   'payoutConfirmed': True,
   'stageId': 4,
   'resultType': 1,
   'sequence': 51},
  {'homeResult': 4,
   'awayResult': 2,
   'resultConfirmType': 3,
   'payoutConfirmed': True,
   'stageId': 5,
   'resultType': 1,
   'sequence': 52},
  {'homeResult': 5,
   'awayResult': 1,
   'resultConfirmType': 2,
   'payoutConfirmed': True,
   'stageId': 3,
   'resultType': 2,
   'sequence': 53},
  {'homeResult': 6,
   'awayResult': 5,
   'resultConfirmType': 2,
   'payoutConfirmed': True,
   'stageId': 5,
   'resultType': 2,
   'sequence': 54}],
 'poolInfo': {'payoutRefundPools': ['HIL',
   'OOE',
   'HFT',
   'TTG',
   'LGS',
   'CHL',
   'FCH',
   'FHA',
   'FGS',
   'HHA',
   'FCS',
   'FHL',
   'CRS',
   'HAD',
   'FTS',
   'AGS',
   'HDC'],
  'refundPools': ['LGS'],
  'ntsInfo': [],
  'entInfo': [],
  'definedPools': ['HIL',
   'OOE',
   'HFT',
   'TTG',
   'LGS',
   'CHL',
   'FCH',
   'FHA',
   'FGS',
   'HHA',
   'FCS',
   'FHL',
   'CRS',
   'HAD',
   'FTS',
   'AGS',
   'HDC']}}

In [29]:
match_records_list[0]["id"], match_records_list[1]["id"]

('50060631', '50060535')

In [9]:
with open("../../../../sample_data/match_data/match_records_real_madrid_sample_20260612.json", "w") as f:
    f.write(json.dumps(match_records_list))

## 3. Test Query for Match Results

In [13]:
match_result = hkjc_fb_dp.get_match_result(
    match_id="50060631",
)
match_result

{'id': '50060631',
 'foPools': [{'id': '1420671003',
   'status': 'PAYOUTSTARTED',
   'oddsType': 'HIL',
   'instNo': 0,
   'name_ch': '',
   'name_en': '',
   'lines': [{'combinations': [{'str': 'H',
       'status': 'WIN',
       'winOrd': '1',
       'selections': [{'selId': '1',
         'str': 'H',
         'name_ch': '大',
         'name_en': 'High'}]},
      {'str': 'L',
       'status': 'LOSE',
       'winOrd': '2',
       'selections': [{'selId': '2',
         'str': 'L',
         'name_ch': '細',
         'name_en': 'Low'}]}]},
    {'combinations': [{'str': 'H',
       'status': 'WIN',
       'winOrd': '1',
       'selections': [{'selId': '1',
         'str': 'H',
         'name_ch': '大',
         'name_en': 'High'}]},
      {'str': 'L',
       'status': 'LOSE',
       'winOrd': '2',
       'selections': [{'selId': '2',
         'str': 'L',
         'name_ch': '細',
         'name_en': 'Low'}]}]},
    {'combinations': [{'str': 'H',
       'status': 'WIN',
       'winOrd': '1',
       'selections': [{'selId': '1',
         'str': 'H',
         'name_ch': '大',
         'name_en': 'High'}]},
      {'str': 'L',
       'status': 'LOSE',
       'winOrd': '2',
       'selections': [{'selId': '2',
         'str': 'L',
         'name_ch': '細',
         'name_en': 'Low'}]}]}]},
  {'id': '1420680012',
   'status': 'PAYOUTSTARTED',
   'oddsType': 'TTG',
   'instNo': 0,
   'name_ch': '',
   'name_en': '',
   'lines': [{'combinations': [{'str': '0',
       'status': 'LOSE',
       'winOrd': '1',
       'selections': [{'selId': '1',
         'str': '0',
         'name_ch': '0',
         'name_en': '0'}]},
      {'str': '1',
       'status': 'LOSE',
       'winOrd': '2',
       'selections': [{'selId': '2',
         'str': '1',
         'name_ch': '1',
         'name_en': '1'}]},
      {'str': '2',
       'status': 'LOSE',
       'winOrd': '3',
       'selections': [{'selId': '3',
         'str': '2',
         'name_ch': '2',
         'name_en': '2'}]},
      {'str': '3',
       'status': 'LOSE',
       'winOrd': '4',
       'selections': [{'selId': '4',
         'str': '3',
         'name_ch': '3',
         'name_en': '3'}]},
      {'str': '4',
       'status': 'LOSE',
       'winOrd': '5',
       'selections': [{'selId': '5',
         'str': '4',
         'name_ch': '4',
         'name_en': '4'}]},
      {'str': '5',
       'status': 'LOSE',
       'winOrd': '6',
       'selections': [{'selId': '6',
         'str': '5',
         'name_ch': '5',
         'name_en': '5'}]},
      {'str': '6',
       'status': 'WIN',
       'winOrd': '7',
       'selections': [{'selId': '7',
         'str': '6',
         'name_ch': '6',
         'name_en': '6'}]},
      {'str': '7+',
       'status': 'LOSE',
       'winOrd': '8',
       'selections': [{'selId': '8',
         'str': '7+',
         'name_ch': '7+',
         'name_en': '7+'}]}]}]},
  {'id': '1420673005',
   'status': 'PAYOUTSTARTED',
   'oddsType': 'CHL',
   'instNo': 0,
   'name_ch': '',
   'name_en': '',
   'lines': [{'combinations': [{'str': 'H',
       'status': 'WIN',
       'winOrd': '1',
       'selections': [{'selId': '1',
         'str': 'H',
         'name_ch': '大',
         'name_en': 'High'}]},
      {'str': 'L',
       'status': 'LOSE',
       'winOrd': '2',
       'selections': [{'selId': '2',
         'str': 'L',
         'name_ch': '細',
         'name_en': 'Low'}]}]},
    {'combinations': [{'str': 'H',
       'status': 'WIN',
       'winOrd': '1',
       'selections': [{'selId': '1',
         'str': 'H',
         'name_ch': '大',
         'name_en': 'High'}]},
      {'str': 'L',
       'status': 'LOSE',
       'winOrd': '2',
       'selections': [{'selId': '2',
         'str': 'L',
         'name_ch': '細',
         'name_en': 'Low'}]}]},
    {'combinations': [{'str': 'H',
       'status': 'LOSE',
       'winOrd': '1',
       'selections': [{'selId': '1',
         'str': 'H',
         'name_ch': '大',
         'name_en': 'High'}]},
      {'str': 'L',
       'status': 'WIN',
       'winOrd': '2',
       'selections': [{'selId': '2',
         'str': 'L',
         'name_ch': '細',
         'name_en': 'Low'}]}]}]},
  {'id': '1420683045',
   'status': 'PAYOUTSTARTED',
   'oddsType': 'FCH',
   'instNo': 0,
   'name_ch': '',
   'name_en': '',
   'lines': [{'combinations': [{'str': 'H',
       'status': 'WIN',
       'winOrd': '1',
       'selections': [{'selId': '1',
         'str': 'H',
         'name_ch': '大',
         'name_en': 'High'}]},
      {'str': 'L',
       'status': 'LOSE',
       'winOrd': '2',
       'selections': [{'selId': '2',
         'str': 'L',
         'name_ch': '細',
         'name_en': 'Low'}]}]},
    {'combinations': [{'str': 'H',
       'status': 'WIN',
       'winOrd': '1',
       'selections': [{'selId': '1',
         'str': 'H',
         'name_ch': '大',
         'name_en': 'High'}]},
      {'str': 'L',
       'status': 'LOSE',
       'winOrd': '2',
       'selections': [{'selId': '2',
         'str': 'L',
         'name_ch': '細',
         'name_en': 'Low'}]}]},
    {'combinations': [{'str': 'H',
       'status': 'LOSE',
       'winOrd': '1',
       'selections': [{'selId': '1',
         'str': 'H',
         'name_ch': '大',
         'name_en': 'High'}]},
      {'str': 'L',
       'status': 'WIN',
       'winOrd': '2',
       'selections': [{'selId': '2',
         'str': 'L',
         'name_ch': '細',
         'name_en': 'Low'}]}]}]},
  {'id': '1420670002',
   'status': 'PAYOUTSTARTED',
   'oddsType': 'FHA',
   'instNo': 0,
   'name_ch': '',
   'name_en': '',
   'lines': [{'combinations': [{'str': 'H',
       'status': 'WIN',
       'winOrd': '1',
       'selections': [{'selId': '1',
         'str': 'H',
         'name_ch': '主隊勝',
         'name_en': 'Home'}]},
      {'str': 'A',
       'status': 'LOSE',
       'winOrd': '3',
       'selections': [{'selId': '2',
         'str': 'A',
         'name_ch': '客隊勝',
         'name_en': 'Away'}]},
      {'str': 'D',
       'status': 'LOSE',
       'winOrd': '2',
       'selections': [{'selId': '3',
         'str': 'D',
         'name_ch': '和',
         'name_en': 'Draw'}]}]}]},
  {'id': '1420675007',
   'status': 'PAYOUTSTARTED',
   'oddsType': 'HHA',
   'instNo': 0,
   'name_ch': '',
   'name_en': '',
   'lines': [{'combinations': [{'str': 'A',
       'status': 'LOSE',
       'winOrd': '3',
       'selections': [{'selId': '2',
         'str': 'A',
         'name_ch': '客隊勝',
         'name_en': 'Away'}]},
      {'str': 'D',
       'status': 'LOSE',
       'winOrd': '2',
       'selections': [{'selId': '3',
         'str': 'D',
         'name_ch': '和',
         'name_en': 'Draw'}]},
      {'str': 'H',
       'status': 'WIN',
       'winOrd': '1',
       'selections': [{'selId': '1',
         'str': 'H',
         'name_ch': '主隊勝',
         'name_en': 'Home'}]}]},
    {'combinations': [{'str': 'H',
       'status': 'WIN',
       'winOrd': '1',
       'selections': [{'selId': '1',
         'str': 'H',
         'name_ch': '主隊勝',
         'name_en': 'Home'}]},
      {'str': 'A',
       'status': 'LOSE',
       'winOrd': '3',
       'selections': [{'selId': '2',
         'str': 'A',
         'name_ch': '客隊勝',
         'name_en': 'Away'}]},
      {'str': 'D',
       'status': 'LOSE',
       'winOrd': '2',
       'selections': [{'selId': '3',
         'str': 'D',
         'name_ch': '和',
         'name_en': 'Draw'}]}]}]},
  {'id': '1420678010',
   'status': 'PAYOUTSTARTED',
   'oddsType': 'FCS',
   'instNo': 0,
   'name_ch': '',
   'name_en': '',
   'lines': [{'combinations': [{'str': '03:03',
       'status': 'LOSE',
       'winOrd': '32',
       'selections': [{'selId': '30',
         'str': '3:3',
         'name_ch': '3:3',
         'name_en': '3:3'}]},
      {'str': 'DO',
       'status': 'LOSE',
       'winOrd': '33',
       'selections': [{'selId': '31',
         'str': 'DO',
         'name_ch': '和其他',
         'name_en': 'Draw Others'}]},
      {'str': 'OHN',
       'status': 'LOSE',
       'winOrd': '13',
       'selections': [{'selId': '32',
         'str': 'HOAN',
         'name_ch': '主其他(客無入球)',
         'name_en': 'Home Others (Away No Goal)'}]},
      {'str': 'OAN',
       'status': 'LOSE',
       'winOrd': '27',
       'selections': [{'selId': '33',
         'str': 'AOHN',
         'name_ch': '客其他(主無入球)',
         'name_en': 'Away Others (Home No Goal)'}]},
      {'str': '01:01',
       'status': 'LOSE',
       'winOrd': '30',
       'selections': [{'selId': '28',
         'str': '1:1',
         'name_ch': '1:1',
         'name_en': '1:1'}]},
      {'str': '02:02',
       'status': 'LOSE',
       'winOrd': '31',
       'selections': [{'selId': '29',
         'str': '2:2',
         'name_ch': '2:2',
         'name_en': '2:2'}]},
      {'str': '00:04',
       'status': 'LOSE',
       'winOrd': '21',
       'selections': [{'selId': '20',
         'str': '0:4',
         'name_ch': '0:4',
         'name_en': '0:4'}]},
      {'str': '01:04',
       'status': 'LOSE',
       'winOrd': '22',
       'selections': [{'selId': '21',
         'str': '1:4',
         'name_ch': '1:4',
         'name_en': '1:4'}]},
      {'str': '02:04',
       'status': 'LOSE',
       'winOrd': '23',
       'selections': [{'selId': '22',
         'str': '2:4',
         'name_ch': '2:4',
         'name_en': '2:4'}]},
      {'str': '00:05',
       'status': 'LOSE',
       'winOrd': '24',
       'selections': [{'selId': '23',
         'str': '0:5',
         'name_ch': '0:5',
         'name_en': '0:5'}]},
      {'str': '01:05',
       'status': 'LOSE',
       'winOrd': '25',
       'selections': [{'selId': '24',
         'str': '1:5',
         'name_ch': '1:5',
         'name_en': '1:5'}]},
      {'str': '02:05',
       'status': 'LOSE',
       'winOrd': '26',
       'selections': [{'selId': '25',
         'str': '2:5',
         'name_ch': '2:5',
         'name_en': '2:5'}]},
      {'str': 'AO',
       'status': 'LOSE',
       'winOrd': '28',
       'selections': [{'selId': '26',
         'str': 'AOHS',
         'name_ch': '客其他(主有入球)',
         'name_en': 'Away Others (Home Scores)'}]},
      {'str': '00:00',
       'status': 'LOSE',
       'winOrd': '29',
       'selections': [{'selId': '27',
         'str': '0:0',
         'name_ch': '0:0',
         'name_en': '0:0'}]},
      {'str': '00:02',
       'status': 'LOSE',
       'winOrd': '16',
       'selections': [{'selId': '15',
         'str': '0:2',
         'name_ch': '0:2',
         'name_en': '0:2'}]},
      {'str': '05:00',
       'status': 'LOSE',
       'winOrd': '10',
       'selections': [{'selId': '10',
         'str': '5:0',
         'name_ch': '5:0',
         'name_en': '5:0'}]},
      {'str': '05:01',
       'status': 'LOSE',
       'winOrd': '11',
       'selections': [{'selId': '11',
         'str': '5:1',
         'name_ch': '5:1',
         'name_en': '5:1'}]},
      {'str': '05:02',
       'status': 'LOSE',
       'winOrd': '12',
       'selections': [{'selId': '12',
         'str': '5:2',
         'name_ch': '5:2',
         'name_en': '5:2'}]},
      {'str': 'HO',
       'status': 'LOSE',
       'winOrd': '14',
       'selections': [{'selId': '13',
         'str': 'HOAS',
         'name_ch': '主其他(客有入球)',
         'name_en': 'Home Others (Away Scores)'}]},
      {'str': '00:01',
       'status': 'LOSE',
       'winOrd': '15',
       'selections': [{'selId': '14',
         'str': '0:1',
         'name_ch': '0:1',
         'name_en': '0:1'}]},
      {'str': '01:02',
       'status': 'LOSE',
       'winOrd': '17',
       'selections': [{'selId': '16',
         'str': '1:2',
         'name_ch': '1:2',
         'name_en': '1:2'}]},
      {'str': '00:03',
       'status': 'LOSE',
       'winOrd': '18',
       'selections': [{'selId': '17',
         'str': '0:3',
         'name_ch': '0:3',
         'name_en': '0:3'}]},
      {'str': '01:03',
       'status': 'LOSE',
       'winOrd': '19',
       'selections': [{'selId': '18',
         'str': '1:3',
         'name_ch': '1:3',
         'name_en': '1:3'}]},
      {'str': '02:03',
       'status': 'LOSE',
       'winOrd': '20',
       'selections': [{'selId': '19',
         'str': '2:3',
         'name_ch': '2:3',
         'name_en': '2:3'}]},
      {'str': '01:00',
       'status': 'LOSE',
       'winOrd': '1',
       'selections': [{'selId': '1',
         'str': '1:0',
         'name_ch': '1:0',
         'name_en': '1:0'}]},
      {'str': '02:00',
       'status': 'LOSE',
       'winOrd': '2',
       'selections': [{'selId': '2',
         'str': '2:0',
         'name_ch': '2:0',
         'name_en': '2:0'}]},
      {'str': '02:01',
       'status': 'WIN',
       'winOrd': '3',
       'selections': [{'selId': '3',
         'str': '2:1',
         'name_ch': '2:1',
         'name_en': '2:1'}]},
      {'str': '03:00',
       'status': 'LOSE',
       'winOrd': '4',
       'selections': [{'selId': '4',
         'str': '3:0',
         'name_ch': '3:0',
         'name_en': '3:0'}]},
      {'str': '03:01',
       'status': 'LOSE',
       'winOrd': '5',
       'selections': [{'selId': '5',
         'str': '3:1',
         'name_ch': '3:1',
         'name_en': '3:1'}]},
      {'str': '03:02',
       'status': 'LOSE',
       'winOrd': '6',
       'selections': [{'selId': '6',
         'str': '3:2',
         'name_ch': '3:2',
         'name_en': '3:2'}]},
      {'str': '04:00',
       'status': 'LOSE',
       'winOrd': '7',
       'selections': [{'selId': '7',
         'str': '4:0',
         'name_ch': '4:0',
         'name_en': '4:0'}]},
      {'str': '04:01',
       'status': 'LOSE',
       'winOrd': '8',
       'selections': [{'selId': '8',
         'str': '4:1',
         'name_ch': '4:1',
         'name_en': '4:1'}]},
      {'str': '04:02',
       'status': 'LOSE',
       'winOrd': '9',
       'selections': [{'selId': '9',
         'str': '4:2',
         'name_ch': '4:2',
         'name_en': '4:2'}]}]}]},
  {'id': '1420672004',
   'status': 'PAYOUTSTARTED',
   'oddsType': 'FHL',
   'instNo': 0,
   'name_ch': '',
   'name_en': '',
   'lines': [{'combinations': [{'str': 'H',
       'status': 'WIN',
       'winOrd': '1',
       'selections': [{'selId': '1',
         'str': 'H',
         'name_ch': '大',
         'name_en': 'High'}]},
      {'str': 'L',
       'status': 'LOSE',
       'winOrd': '2',
       'selections': [{'selId': '2',
         'str': 'L',
         'name_ch': '細',
         'name_en': 'Low'}]}]},
    {'combinations': [{'str': 'H',
       'status': 'WIN',
       'winOrd': '1',
       'selections': [{'selId': '1',
         'str': 'H',
         'name_ch': '大',
         'name_en': 'High'}]},
      {'str': 'L',
       'status': 'LOSE',
       'winOrd': '2',
       'selections': [{'selId': '2',
         'str': 'L',
         'name_ch': '細',
         'name_en': 'Low'}]}]},
    {'combinations': [{'str': 'H',
       'status': 'WIN',
       'winOrd': '1',
       'selections': [{'selId': '1',
         'str': 'H',
         'name_ch': '大',
         'name_en': 'High'}]},
      {'str': 'L',
       'status': 'LOSE',
       'winOrd': '2',
       'selections': [{'selId': '2',
         'str': 'L',
         'name_ch': '細',
         'name_en': 'Low'}]}]}]},
  {'id': '1420677009',
   'status': 'PAYOUTSTARTED',
   'oddsType': 'CRS',
   'instNo': 0,
   'name_ch': '',
   'name_en': '',
   'lines': [{'combinations': [{'str': '00:04',
       'status': 'LOSE',
       'winOrd': '21',
       'selections': [{'selId': '20',
         'str': '0:4',
         'name_ch': '0:4',
         'name_en': '0:4'}]},
      {'str': '01:04',
       'status': 'LOSE',
       'winOrd': '22',
       'selections': [{'selId': '21',
         'str': '1:4',
         'name_ch': '1:4',
         'name_en': '1:4'}]},
      {'str': '02:04',
       'status': 'LOSE',
       'winOrd': '23',
       'selections': [{'selId': '22',
         'str': '2:4',
         'name_ch': '2:4',
         'name_en': '2:4'}]},
      {'str': '00:05',
       'status': 'LOSE',
       'winOrd': '24',
       'selections': [{'selId': '23',
         'str': '0:5',
         'name_ch': '0:5',
         'name_en': '0:5'}]},
      {'str': '01:05',
       'status': 'LOSE',
       'winOrd': '25',
       'selections': [{'selId': '24',
         'str': '1:5',
         'name_ch': '1:5',
         'name_en': '1:5'}]},
      {'str': '02:05',
       'status': 'LOSE',
       'winOrd': '26',
       'selections': [{'selId': '25',
         'str': '2:5',
         'name_ch': '2:5',
         'name_en': '2:5'}]},
      {'str': 'AO',
       'status': 'LOSE',
       'winOrd': '28',
       'selections': [{'selId': '26',
         'str': 'AOHS',
         'name_ch': '客其他(主有入球)',
         'name_en': 'Away Others (Home Scores)'}]},
      {'str': '00:00',
       'status': 'LOSE',
       'winOrd': '29',
       'selections': [{'selId': '27',
         'str': '0:0',
         'name_ch': '0:0',
         'name_en': '0:0'}]},
      {'str': '01:01',
       'status': 'LOSE',
       'winOrd': '30',
       'selections': [{'selId': '28',
         'str': '1:1',
         'name_ch': '1:1',
         'name_en': '1:1'}]},
      {'str': '02:02',
       'status': 'LOSE',
       'winOrd': '31',
       'selections': [{'selId': '29',
         'str': '2:2',
         'name_ch': '2:2',
         'name_en': '2:2'}]},
      {'str': '03:03',
       'status': 'LOSE',
       'winOrd': '32',
       'selections': [{'selId': '30',
         'str': '3:3',
         'name_ch': '3:3',
         'name_en': '3:3'}]},
      {'str': 'DO',
       'status': 'LOSE',
       'winOrd': '33',
       'selections': [{'selId': '31',
         'str': 'DO',
         'name_ch': '和其他',
         'name_en': 'Draw Others'}]},
      {'str': 'OHN',
       'status': 'LOSE',
       'winOrd': '13',
       'selections': [{'selId': '32',
         'str': 'HOAN',
         'name_ch': '主其他(客無入球)',
         'name_en': 'Home Others (Away No Goal)'}]},
      {'str': 'OAN',
       'status': 'LOSE',
       'winOrd': '27',
       'selections': [{'selId': '33',
         'str': 'AOHN',
         'name_ch': '客其他(主無入球)',
         'name_en': 'Away Others (Home No Goal)'}]},
      {'str': '01:02',
       'status': 'LOSE',
       'winOrd': '17',
       'selections': [{'selId': '16',
         'str': '1:2',
         'name_ch': '1:2',
         'name_en': '1:2'}]},
      {'str': '05:00',
       'status': 'LOSE',
       'winOrd': '10',
       'selections': [{'selId': '10',
         'str': '5:0',
         'name_ch': '5:0',
         'name_en': '5:0'}]},
      {'str': '05:01',
       'status': 'LOSE',
       'winOrd': '11',
       'selections': [{'selId': '11',
         'str': '5:1',
         'name_ch': '5:1',
         'name_en': '5:1'}]},
      {'str': '05:02',
       'status': 'LOSE',
       'winOrd': '12',
       'selections': [{'selId': '12',
         'str': '5:2',
         'name_ch': '5:2',
         'name_en': '5:2'}]},
      {'str': 'HO',
       'status': 'LOSE',
       'winOrd': '14',
       'selections': [{'selId': '13',
         'str': 'HOAS',
         'name_ch': '主其他(客有入球)',
         'name_en': 'Home Others (Away Scores)'}]},
      {'str': '00:01',
       'status': 'LOSE',
       'winOrd': '15',
       'selections': [{'selId': '14',
         'str': '0:1',
         'name_ch': '0:1',
         'name_en': '0:1'}]},
      {'str': '00:02',
       'status': 'LOSE',
       'winOrd': '16',
       'selections': [{'selId': '15',
         'str': '0:2',
         'name_ch': '0:2',
         'name_en': '0:2'}]},
      {'str': '00:03',
       'status': 'LOSE',
       'winOrd': '18',
       'selections': [{'selId': '17',
         'str': '0:3',
         'name_ch': '0:3',
         'name_en': '0:3'}]},
      {'str': '01:03',
       'status': 'LOSE',
       'winOrd': '19',
       'selections': [{'selId': '18',
         'str': '1:3',
         'name_ch': '1:3',
         'name_en': '1:3'}]},
      {'str': '02:03',
       'status': 'LOSE',
       'winOrd': '20',
       'selections': [{'selId': '19',
         'str': '2:3',
         'name_ch': '2:3',
         'name_en': '2:3'}]},
      {'str': '01:00',
       'status': 'LOSE',
       'winOrd': '1',

In [30]:
match_results = hkjc_fb_dp.get_match_results_in_batch(
    match_id_list=['50060631', '50060535'],
)
len(match_results)

2

In [15]:
match_results[1].keys()

dict_keys(['id', 'foPools', 'additionalResults'])

In [32]:
with open("../../../../sample_data/match_data/match_results_sample_20260612.json", "w") as f:
    f.write(json.dumps(match_results))

## 4. Test Query for Match Odds

In [33]:
match_odds = hkjc_fb_dp.get_match_odds_in_batch(
    match_id_list=['50060631', '50060535'],
)
len(match_odds)

2

In [17]:
match_odds[1].keys()

dict_keys(['id', 'updateAt', 'statusUpdatedAt', 'foPools'])

In [39]:
with open("../../../../sample_data/match_data/match_odds_sample_20260612.json", "w") as f:
    f.write(json.dumps(match_odds, indent=4))

## 5. Test Query for All Live Matches

In [18]:
all_live_matches = hkjc_fb_dp.get_all_live_matches()
print(len(all_live_matches))

148

In [20]:
all_live_matches[0]

{'id': '50068133',
 'frontEndId': 'FB0006',
 'matchDate': '2026-06-14+08:00',
 'kickOffTime': '2026-06-14T06:00:00.000+08:00',
 'status': 'PREEVENT',
 'updateAt': '2026-06-12T23:21:34.607+08:00',
 'sequence': '0.1781366400.52.Finnish Division 1                                                                                                              .0.99.IFK Mariehamn                                                                                                                   .005',
 'esIndicatorEnabled': True,
 'homeTeam': {'id': '50000524', 'name_en': 'Brazil', 'name_ch': '巴西'},
 'awayTeam': {'id': '50002168', 'name_en': 'Morocco', 'name_ch': '摩洛哥'},
 'tournament': {'id': '50068132',
  'frontEndId': 'FB8695',
  'nameProfileId': '50000118',
  'sequence': '01.WC Finals                                                                                                                       .2026-07-21.000',
  'isInteractiveServiceAvailable': True,
  'code': 'WCC',
  'name_en': 'WC Finals',
  'name_ch': '世盃'},
 'isInteractiveServiceAvailable': True,
 'inplayDelay': False,
 'venue': {'code': 'USA030',
  'name_en': 'MetLife Stadium',
  'name_ch': '大都會人壽體育場'},
 'tvChannels': [{'code': '618', 'name_en': 'Now 618', 'name_ch': 'Now 618'},
  {'code': '616', 'name_en': 'Now 616', 'name_ch': 'Now 616'}],
 'liveEvents': [{'id': '66456928', 'code': 'BETRADAR'}],
 'featureStartTime': '',
 'featureMatchSequence': '',
 'poolInfo': {'normalPools': ['SGA1',
   'CHA',
   'CHD',
   'SGA10',
   'FLH',
   'TTG',
   'SGA5',
   'SGA11',
   'HDC',
   'CHH',
   'SGA3',
   'MSP5',
   'HAD',
   'CRS',
   'CFH',
   'SGA20',
   'SGA13',
   'OOE',
   'FHL',
   'AGS',
   'FHC',
   'SGA8',
   'LGS',
   'MSP1',
   'MSP2',
   'CHL',
   'SGA7',
   'SGA14',
   'HIL',
   'FCS',
   'SGA2',
   'HLH',
   'FHH',
   'CFA',
   'SGA18',
   'MSP3',
   'SGA17',
   'FCH',
   'SGA4',
   'SGA19',
   'HLA',
   'FGS',
   'FHA',
   'SGA15',
   'FLA',
   'SGA12',
   'HHA',
   'HFT',
   'SGA6',
   'MSP4',
   'FTS',
   'SGA16',
   'SGA9'],
  'inplayPools': ['CHA',
   'CHD',
   'FLH',
   'TTG',
   'HDC',
   'CHH',
   'HAD',
   'CRS',
   'CFH',
   'FHL',
   'AGS',
   'FHC',
   'CHL',
   'HIL',
   'FCS',
   'HLH',
   'FHH',
   'CFA',
   'FCH',
   'HLA',
   'FHA',
   'FLA',
   'HHA'],
  'sellingPools': ['SGA1',
   'CHA',
   'CHD',
   'SGA10',
   'FLH',
   'TTG',
   'SGA5',
   'SGA11',
   'HDC',
   'CHH',
   'SGA3',
   'MSP5',
   'HAD',
   'CRS',
   'CFH',
   'SGA20',
   'SGA13',
   'OOE',
   'FHL',
   'AGS',
   'FHC',
   'SGA8',
   'LGS',
   'MSP1',
   'MSP2',
   'CHL',
   'SGA7',
   'SGA14',
   'HIL',
   'FCS',
   'SGA2',
   'HLH',
   'FHH',
   'CFA',
   'SGA18',
   'MSP3',
   'SGA17',
   'FCH',
   'SGA4',
   'SGA19',
   'HLA',
   'FGS',
   'FHA',
   'SGA15',
   'FLA',
   'SGA12',
   'HHA',
   'HFT',
   'SGA6',
   'MSP4',
   'FTS',
   'SGA16',
   'SGA9'],
  'ntsInfo': [],
  'entInfo': [],
  'definedPools': ['SGA1',
   'CHA',
   'CHD',
   'SGA10',
   'FLH',
   'TTG',
   'SGA5',
   'SGA11',
   'HDC',
   'CHH',
   'SGA3',
   'MSP5',
   'HAD',
   'CRS',
   'CFH',
   'SGA20',
   'SGA13',
   'OOE',
   'FHL',
   'AGS',
   'FHC',
   'SGA8',
   'LGS',
   'MSP1',
   'MSP2',
   'CHL',
   'SGA7',
   'SGA14',
   'HIL',
   'FCS',
   'SGA2',
   'HLH',
   'FHH',
   'CFA',
   'SGA18',
   'MSP3',
   'SGA17',
   'FCH',
   'SGA4',
   'SGA19',
   'HLA',
   'FGS',
   'FHA',
   'SGA15',
   'FLA',
   'SGA12',
   'HHA',
   'HFT',
   'SGA6',
   'MSP4',
   'FTS',
   'SGA16',
   'SGA9'],
  'ngsInfo': [],
  'agsInfo': []},
 'runningResult': None,
 'runningResultExtra': None,
 'adminOperation': {'remark': None}}

In [22]:
all_live_matches[0].keys()

dict_keys(['id', 'frontEndId', 'matchDate', 'kickOffTime', 'status', 'updateAt', 'sequence', 'esIndicatorEnabled', 'homeTeam', 'awayTeam', 'tournament', 'isInteractiveServiceAvailable', 'inplayDelay', 'venue', 'tvChannels', 'liveEvents', 'featureStartTime', 'featureMatchSequence', 'poolInfo', 'runningResult', 'runningResultExtra', 'adminOperation'])

In [23]:
for match in all_live_matches:
    print(f"{match['homeTeam']['name_ch']} v.s. {match['awayTeam']['name_ch']}")

巴西 v.s. 摩洛哥
葡萄牙 v.s. 剛果民主共和國
土耳其 v.s. 巴拉圭
天主教大學 v.s. 康塞普森大學
海地 v.s. 蘇格蘭
瑞典 v.s. 突尼西亞
伊朗 v.s. 新西蘭
墨西哥 v.s. 南韓
厄瓜多爾 v.s. 庫拉索
拉迪 v.s. 施拿祖基
荷蘭 v.s. 瑞典
西悉尼流浪者B隊 v.s. 聖佐治城
卡塔爾 v.s. 瑞士
巴拿馬 v.s. 克羅地亞
巴西 v.s. 海地
烏拉圭 v.s. 西班牙
薩瑟蘭鯊魚 v.s. 黑鎮城
荷蘭 v.s. 日本
馬可尼駿馬 v.s. FC悉尼B隊
德國 v.s. 庫拉索
巴拿馬 v.s. 英格蘭
法國 v.s. 伊拉克
高路高路 v.s. 科布雷素
澳洲 v.s. 土耳其
科特迪瓦 v.s. 厄瓜多爾
加拿大 v.s. 瑞士
新西蘭 v.s. 埃及
臥龍崗狼隊 v.s. 萊卡特
英格蘭 v.s. 加納
域斯祖女足 v.s. 基斯迪史達斯女足
約旦 v.s. 阿爾及利亞
黃金海岸騎士 v.s. 布里斯班東區
蘇格蘭 v.s. 摩洛哥
美國 v.s. 巴拉圭
水原FC女足 v.s. 世宗FC女足
西班牙 v.s. 佛得角
華拉倫加女足 v.s. 白蘭恩女足
紐柏萊斯 v.s. 侯治柏度
加納 v.s. 巴拿馬
阿根廷 v.s. 奧地利
沙特阿拉伯 v.s. 烏拉圭
伊拉克 v.s. 挪威
哥甘保 v.s. 奧希金斯
阿根廷 v.s. 阿爾及利亞
康塞普森體育 v.s. 利馬切
南韓 v.s. 捷克
國際杜古 v.s. AC奧盧
伊斯韋斯 v.s. TPS杜古
瑞士 v.s. 波斯尼亞
德國 v.s. 科特迪瓦
利恩女足 v.s. 洛辛堡女足
烏拉圭 v.s. 佛得角
新西蘭 v.s. 比利時
戈亞尼恩斯 v.s. CRB
南非 v.s. 南韓
曼利聯 v.s. 悉尼聯
美國 v.s. 澳洲
奧地利 v.s. 約旦
洛克達爾以利亞日 v.s. 南區奇兵
維拿迪馬愛華頓 v.s. 柏利斯天奴
NWS精神 v.s. 悉尼奧林匹克
法國 v.s. 塞內加爾
比利時 v.s. 伊朗
比利時 v.s. 埃及
摩洛哥 v.s. 海地
奧達斯 v.s. 拿沙連拿
北極星FC v.s. 半島電力
捷克 v.s. 南非
查路 v.s. 赫爾辛基
加拿大 v.s. 波斯尼亞
VPS華沙 v.s. 古比斯
加拿大 v.s. 卡塔爾
挪威 v.s. 塞內加爾
馬利漢 v.s. 格尼斯坦
烏茲別克 v.s. 哥倫比亞
西班牙 v.s. 沙特阿拉伯
英格蘭 v.s. 克羅地亞
突尼西亞 v.s. 日本
黃金海岸聯 v.s. 布里斯班城
新南威爾斯大學FC v.s. 聖佐治FC
哥倫比亞 v.s. 剛果民主共和國
美國 v.s. 土耳其
哥倫比亞 v.s. 葡萄牙
葡萄牙 v.s. 烏茲別克
突尼西亞 v.s. 荷蘭
克羅地亞 v.s. 加納
日本 v.s. 瑞典
庫拉索 v.s. 科特迪瓦
埃及 v.s. 伊朗
蘇格蘭 v.s. 巴西
挪威 v.s. 法國
約旦 v.s. 阿根廷
巴拉圭 v.s. 澳洲
剛果民主共和國 v.s. 烏茲別克
波斯尼亞 v.s. 卡塔爾
阿爾及利亞 v.s. 奧地利
厄瓜多爾 v.s. 德國
墨西哥 v.s. 捷克
佛得角 v.s. 沙特阿拉伯
塞內加爾 v.s. 伊拉克
洛亞女足 v.s. 漢福斯女足
巴基斯坦 v.s. 阿富汗
利斯菲體育會 v.s. 競技體育會
LSK基文拿女足 v.s. 阿里辛特女足
譚柏灣暴徒 v.s. 查勒斯頓炮台
侯格辛特女足 v.s. 波杜基林特女足
馬拉加 v.s. 艾美利亞
康津天鵝女足 v.s. 首爾城女足
底特律城 v.s. 艾爾帕索火車頭
蒙特雷灣 v.s. 傑克遜維爾體育會
戈亞斯 v.s. 路禾利桑天奴
鳳凰城復活 v.s. 路易斯維爾城
墨西哥 v.s. 南非
聞慶尚武女足 v.s. 慶州FC女足
葡萄牙 v.s. 尼日利亞
卡拉雷聯 v.s. 智利大學
馬拉加 v.s. 拉斯彭馬斯
史達比克女足 v.s. 莫迪女足
施亞拉 v.s. 艾華爾
英格蘭 v.s. 哥斯達黎加
洛辛加特女足 v.s. 諾高平女足
艾斯基斯杜拿聯女足 v.s. 馬模女足
勞頓聯 v.s. 羅德島FC
AIK蘇納女足 v.s. 佐加頓斯女足
譚柏灣暴徒 v.s. 哈特福體育
匹茲堡獵犬 v.s. 印地安納十一
哈馬比女足 v.s. 赫根女足
新墨西哥聯 v.s. SC奧蘭治郡
伯明翰軍團 v.s. 拉斯維加斯燈火
奧克蘭根源 v.s. 邁亞密FC
韋克舍女足 v.s. 烏普薩拉女足
艾爾帕索火車頭 v.s. 鳳凰城復活
比堤亞女足 v.s. 布洛馬波卡納女足
列星頓SC v.s. FC聖安東尼奧
查勒斯頓炮台 v.s. FC塔爾薩
聖貝拿度 v.s. 利斯菲體育會
保地花高SP v.s. 奧柏拉里奧
傑克遜維爾體育會 v.s. 底特律城
競技體育會 v.s. 戈亞斯
青年人 v.s. 邦迪比達
路易斯維爾城 v.s. 布魯克林FC
科羅拉多泉坡路 v.s. 薩克拉門托共和
路禾利桑天奴 v.s. 紐迪高
隆德里納 v.s. 艾華爾
古亞巴 v.s. 維拉諾瓦
基斯奧馬 v.s. 施亞拉
陽光海岸流浪者 v.s. FC獅子
卡布爾查體育 v.s. 羅奇代爾流浪

In [38]:
with open("../../../../sample_data/match_data/all_live_matches_sample_20260612.json", "w") as f:
    f.write(json.dumps(all_live_matches, indent=4))

## 5. Test Query for Live Match Data

In [24]:
live_match_data = hkjc_fb_dp.get_live_matches(
    match_id_list=["50069886"]
)
live_match_data

[{'id': '50069886',
  'frontEndId': 'FB0829',
  'matchDate': '2026-06-13+08:00',
  'kickOffTime': '2026-06-13T01:00:00.000+08:00',
  'status': 'SECONDHALF',
  'updateAt': '2026-06-12T05:02:59.080+08:00',
  'sequence': '0.1781283600.94.Women Swedish Division 1                                                                                                        .0.99.Vittsjo Women                                                                                                                   .001',
  'esIndicatorEnabled': True,
  'homeTeam': {'id': '50353896',
   'name_en': 'Vittsjo Women',
   'name_ch': '域斯祖女足'},
  'awayTeam': {'id': '50353890',
   'name_en': 'Kristianstads Women',
   'name_ch': '基斯迪史達斯女足'},
  'tournament': {'id': '50065711',
   'frontEndId': '',
   'nameProfileId': '50651726',
   'isInteractiveServiceAvailable': False,
   'code': 'SALW',
   'name_en': 'Women Swedish Division 1',
   'name_ch': '女子瑞典超級聯賽'},
  'isInteractiveServiceAvailable': True,
  'inplayDelay': True,
  'venue': None,
  'tvChannels': [],
  'liveEvents': [],
  'featureStartTime': '',
  'featureMatchSequence': '',
  'poolInfo': {'normalPools': ['NTS2',
    'HIL',
    'TTG',
    'CHA',
    'CRS',
    'HAD',
    'HDC',
    'HLA',
    'CHL',
    'CHH',
    'HHA',
    'CHD',
    'HLH'],
   'inplayPools': ['NTS2',
    'HIL',
    'TTG',
    'CHA',
    'CRS',
    'HAD',
    'HDC',
    'HLA',
    'CHL',
    'CHH',
    'HHA',
    'CHD',
    'HLH'],
   'sellingPools': ['NTS2',
    'HIL',
    'TTG',
    'CHA',
    'CRS',
    'HAD',
    'HDC',
    'HLA',
    'CHL',
    'CHH',
    'HHA',
    'CHD',
    'HLH'],
   'ntsInfo': ['1:H'],
   'entInfo': [],
   'definedPools': ['SGA20',
    'SGA13',
    'NTS2',
    'HFT',
    'FHH',
    'SGA3',
    'OOE',
    'CFH',
    'FCS',
    'SGA16',
    'HIL',
    'SGA11',
    'SGA19',
    'SGA12',
    'CFA',
    'TTG',
    'SGA9',
    'FHA',
    'FLH',
    'SGA1',
    'SGA17',
    'CHA',
    'SGA7',
    'CRS',
    'FLA',
    'NTS1',
    'SGA18',
    'FTS',
    'HAD',
    'HDC',
    'SGA15',
    'SGA2',
    'HLA',
    'CHL',
    'CHH',
    'SGA8',
    'SGA5',
    'HHA',
    'FCH',
    'SGA4',
    'FHC',
    'SGA6',
    'SGA14',
    'CHD',
    'SGA10',
    'FHL',
    'HLH'],
   'ngsInfo': [],
   'agsInfo': []},
  'runningResult': {'homeScore': 1,
   'awayScore': 0,
   'corner': 1,
   'homeCorner': 0,
   'awayCorner': 1},
  'runningResultExtra': None,
  'adminOperation': {'remark': None},
  'foPools': [{'id': '1714514001',
    'status': 'SELLINGSTARTED',
    'oddsType': 'HAD',
    'instNo': 0,
    'inplay': True,
    'name_ch': '',
    'name_en': '',
    'updateAt': '2026-06-13T01:18:15.741+08:00',
    'expectedSuspendDateTime': '',
    'lines': [{'lineId': '0',
      'status': 'AVAILABLE',
      'condition': '0.0',
      'main': True,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '1.32',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '主隊勝',
          'name_en': 'Home'}]},
       {'combId': '2',
        'str': 'A',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '8.25',
        'selections': [{'selId': '2',
          'str': 'A',
          'name_ch': '客隊勝',
          'name_en': 'Away'}]},
       {'combId': '3',
        'str': 'D',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '3.65',
        'selections': [{'selId': '3',
          'str': 'D',
          'name_ch': '和',
          'name_en': 'Draw'}]}]}]},
   {'id': '1714520007',
    'status': 'SELLINGSTARTED',
    'oddsType': 'HHA',
    'instNo': 0,
    'inplay': True,
    'name_ch': '',
    'name_en': '',
    'updateAt': '2026-06-13T01:18:31.212+08:00',
    'expectedSuspendDateTime': '',
    'lines': [{'lineId': '3',
      'status': 'AVAILABLE',
      'condition': '-2.0',
      'main': True,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '17.00',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '主隊勝',
          'name_en': 'Home'}]},
       {'combId': '3',
        'str': 'D',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '4.05',
        'selections': [{'selId': '3',
          'str': 'D',
          'name_ch': '和',
          'name_en': 'Draw'}]},
       {'combId': '2',
        'str': 'A',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '1.18',
        'selections': [{'selId': '2',
          'str': 'A',
          'name_ch': '客隊勝',
          'name_en': 'Away'}]}]},
     {'lineId': '1',
      'status': 'SUSPENDED',
      'condition': '-1.0',
      'main': False,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '2.90',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '主隊勝',
          'name_en': 'Home'}]},
       {'combId': '3',
        'str': 'D',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '3.16',
        'selections': [{'selId': '3',
          'str': 'D',
          'name_ch': '和',
          'name_en': 'Draw'}]},
       {'combId': '2',
        'str': 'A',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '2.03',
        'selections': [{'selId': '2',
          'str': 'A',
          'name_ch': '客隊勝',
          'name_en': 'Away'}]}]},
     {'lineId': '2',
      'status': 'SUSPENDED',
      'condition': '+1.0',
      'main': False,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '1.10',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '主隊勝',
          'name_en': 'Home'}]},
       {'combId': '3',
        'str': 'D',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '6.70',
        'selections': [{'selId': '3',
          'str': 'D',
          'name_ch': '和',
          'name_en': 'Draw'}]},
       {'combId': '2',
        'str': 'A',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '10.50',
        'selections': [{'selId': '2',
          'str': 'A',
          'name_ch': '客隊勝',
          'name_en': 'Away'}]}]}]},
   {'id': '1714519006',
    'status': 'SELLINGSTARTED',
    'oddsType': 'HDC',
    'instNo': 0,
    'inplay': True,
    'name_ch': '',
    'name_en': '',
    'updateAt': '2026-06-13T01:18:16.515+08:00',
    'expectedSuspendDateTime': '',
    'lines': [{'lineId': '2',
      'status': 'AVAILABLE',
      'condition': '-0.5/-1.0',
      'main': True,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '1.59',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '主隊勝',
          'name_en': 'Home'}]},
       {'combId': '2',
        'str': 'A',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '2.20',
        'selections': [{'selId': '2',
          'str': 'A',
          'name_ch': '客隊勝',
          'name_en': 'Away'}]}]},
     {'lineId': '1',
      'status': 'SUSPENDED',
      'condition': '0.0/+0.5',
      'main': False,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '1.23',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '主隊勝',
          'name_en': 'Home'}]},
       {'combId': '2',
        'str': 'A',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '3.65',
        'selections': [{'selId': '2',
          'str': 'A',
          'name_ch': '客隊勝',
          'name_en': 'Away'}]}]}]},
   {'id': '1714516003',
    'status': 'SELLINGSTARTED',
    'oddsType': 'HIL',
    'instNo': 0,
    'inplay': True,
    'name_ch': '',
    'name_en': '',
    'updateAt': '2026-06-13T01:18:24.360+08:00',
    'expectedSuspendDateTime': '',
    'lines': [{'lineId': '1',
      'status': 'AVAILABLE',
      'condition': '2.5',
      'main': True,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '3.25',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '大',
          'name_en': 'High'}]},
       {'combId': '2',
        'str': 'L',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '1.28',
        'selections': [{'selId': '2',
          'str': 'L',
          'name_ch': '細',
          'name_en': 'Low'}]}]},
     {'lineId': '7',
      'status': 'AVAILABLE',
      'condition': '1.5/2.0',
      'main': False,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '1.72',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '大',
          'name_en': 'High'}]},
       {'combId': '2',
        'str': 'L',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '2.00',
        'selections': [{'selId': '2',
          'str': 'L',
          'name_ch': '細',
          'name_en': 'Low'}]}]},
     {'lineId': '4',
      'status': 'AVAILABLE',
      'condition': '2.0/2.5',
      'main': False,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '2.88',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '大',
          'name_en': 'High'}]},
       {'combId': '2',
        'str': 'L',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '1.35',
        'selections': [{'selId': '2',
          'str': 'L',
          'name_ch': '細',
          'name_en': 'Low'}]}]},
     {'lineId': '2',
      'status': 'SUSPENDED',
      'condition': '2.5/3.0',
      'main': False,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '2.25',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '大',
          'name_en': 'High'}]},
       {'combId': '2',
        'str': 'L',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '1.57',
        'selections': [{'selId': '2',
          'str': 'L',
          'name_ch': '細',
          'name_en': 'Low'}]}]},
     {'lineId': '5',
      'status': 'SUSPENDED',
      'condition': '3.0/3.5',
      'main': False,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '2.20',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '大',
          'name_en': 'High'}]},
       {'combId': '2',
        'str': 'L',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '1.59',
        'selections': [{'selId': '2',
          'str': 'L',
          'name_ch': '細',
          'name_en': 'Low'}]}]},
     {'lineId': '3',
      'status': 'SUSPENDED',
      'condition': '3.5',
      'main': False,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '7.00',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '大',
          'name_en': 'High'}]},
       {'combId': '2',
        'str': 'L',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '1.05',
        'selections': [{'selId': '2',
          'str': 'L',
          'name_ch': '細',
          'name_en': 'Low'}]}]},
     {'lineId': '6',
      'status': 'SUSPENDED',
      'condition': '4.5',
      'main': False,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '4.75',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '大',
          'name_en': 'High'}]},
       {'combId': '2',
        'str': 'L',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '1.13',
        'selections': [{'selId': '2',
          'str': 'L',
          'name_ch': '細',
          'name_en': 'Low'}]}]}]},
   {'id': '1714518005',
    'status': 'SELLINGSTARTED',
    'oddsType': 'CHL',
    'instNo': 0,
    'inplay': True,
    'name_ch': '',
    'name_en': '',
    'updateAt': '2026-06-13T01:25:39.130+08:00',
    'expectedSuspendDateTime': '',
    'lines': [{'lineId': '10',
      'status': 'AVAILABLE',
      'condition': '3.5',
      'main': True,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '2.20',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '大',
          'name_en': 'High'}]},
       {'combId': '2',
        'str': 'L',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '1.59',
        'selections': [{'selId': '2',
          'str': 'L',
          'name_ch': '細',
          'name_en': 'Low'}]}]},
     {'lineId': '9',
      'status': 'AVAILABLE',
      'condition': '4.5',
      'main': False,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '3.55',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '大',
          'name_en': 'High'}]},
       {'combId': '2',
        'str': 'L',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '1.24',
        'selections': [{'selId': '2',
          'str': 'L',
          'name_ch': '細',
          'name_en': 'Low'}]}]},
     {'lineId': '8',
      'status': 'AVAILABLE',
      'condition': '5.5',
      'main': False,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '5.90',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '大',
          'name_en': 'High'}]},
       {'combId': '2',
        'str': 'L',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '1.08',
        'selections': [{'selId': '2',
          'str': 'L',
          'name_ch': '細',
          'name_en': 'Low'}]}]},
     {'lineId': '7',
      'status': 'SUSPENDED',
      'condition': '6.5',
      'main': False,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '4.95',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '大',
          'name_en': 'High'}]},
       {'combId': '2',
        'str': 'L',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '1.12',
        'selections': [{'selId': '2',
          'str': 'L',
          'name_ch': '細',
          'name_en': 'Low'}]}]},
     {'lineId': '6',
      'status': 'SUSPENDED',
      'condition': '7.5',
      'main': False,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '4.60',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '大',
          'name_en': 'High'}]},
       {'combId': '2',
        'str': 'L',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '1.14',
        'selections': [{'selId': '2',
          'str': 'L',
          'name_ch': '細',
          'name_en': 'Low'}]}]},
     {'lineId': '5',
      'status': 'SUSPENDED',
      'condition': '8.5',
      'main': False,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '4.30',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '大',
          'name_en': 'High'}]},
       {'combId': '2',
        'str': 'L',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '1.16',
        'selections': [{'selId': '2',
          'str': 'L',
          'name_ch': '細',
          'name_en': 'Low'}]}]},
     {'lineId': '1',
      'status': 'SUSPENDED',
      'condition': '9.5',
      'main': False,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '3.80',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '大',
          'name_en': 'High'}]},
       {'combId': '2',
        'str': 'L',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '1.21',
        'selections': [{'selId': '2',
          'str': 'L',
          'name_ch': '細',
          'name_en': 'Low'}]}]},
     {'lineId': '2',
      'status': 'SUSPENDED',
      'condition': '10.5',
      'main': False,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '3.45',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '大',
          'name_en': 'High'}]},
       {'combId': '2',
        'str': 'L',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '1.25',
        'selections': [{'selId': '2',
          'str': 'L',
          'name_ch': '細',
          'name_en': 'Low'}]}]},
     {'lineId': '4',
      'status': 'SUSPENDED',
      'condition': '11.5',
      'main': False,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '3.45',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '大',
          'name_en': 'High'}]},
       {'combId': '2',
        'str': 'L',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '1.25',
        'selections': [{'selId': '2',
          'str': 'L',
          'name_ch': '細',
          'name_en': 'Low'}]}]},
     {'lineId': '3',
      'status': 'SUSPENDED',
      'condition': '13.5',
      'main': False,
      'combinations': [{'combId': '1',
        'str': 'H',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '4.40',
        'selections': [{'selId': '1',
          'str': 'H',
          'name_ch': '大',
          'name_en': 'High'}]},
       {'combId': '2',
        'str': 'L',
        'status': 'AVAILABLE',
        'offerEarlySettlement': 'Offer',
        'currentOdds': '1.15',
        'selections': [{'selId': '2',
          'str': 'L',
          'name_ch': '細',
          'name_en': 'Low'}]}]}]},
   {'id': '1714522009',
    'status': 'SELLINGSTARTED',
    'oddsType': 'CRS',
    'instNo': 0,
    'inplay': True,
    'name_ch': '',
    'name_en': '',
    'updateAt': '2026-06-13T01:18:37.435+08:00',
    'expectedSuspendDateTime': '',
    'lines': [{'lineId': '0',
      'status': 'AVAILABLE',
      'condition': '0.0',
      'main': True,
      'combinations': [{'combId': '1',
        'str': '01:00',

In [40]:
with open("../../../../sample_data/match_data/live_match_data_sample_20260612.json", "w") as f:
    f.write(json.dumps(live_match_data, indent=4))