In [2]:
# Import Libraries
## Standard Libraries
import datetime
import json
import os
import sys

## Third-Party Libraries
import pandas as pd

## Local Libraries
sys.path.append("../../..")
from v2.scraper import LiveMatchScraper, MatchRecordsScraper, TeamIDScraper

## 1. Test Query for Team IDs

In [3]:
team_id_scraper = TeamIDScraper()
team_id_dict = team_id_scraper.get_team_ids()
team_info_df = pd.DataFrame(team_id_dict["data"]["teamList"])
team_info_df.head()

         id code  name_ch               name_en
0  50000001  TMN  1860慕尼黑           1860 Munich
1  50430573  WBA  3B亞馬遜女足  3B da Amazonia Women
2  50000002  OCT     十月九日          9 de Octubre
3  50000003  AAS    澳職明星隊    A-League All Stars
4  50000004  AAG       真特               AA Gent

In [4]:
team_info_df.loc[team_info_df["name_en"] == "Real Madrid"]

            id code name_ch      name_en
4085  50002589  RMD   皇家馬德里  Real Madrid

## 2. Test Query for Historical Matches

In [5]:
match_records_scraper = MatchRecordsScraper()
match_records_list = match_records_scraper.get_historical_matches(
    start_date=datetime.date(2024, 11, 1),
    end_date=datetime.date(2025, 1, 23),
    team_id="50002589",
)

In [6]:
len(match_records_list)

18

In [7]:
match_records_list[0].keys()

dict_keys(['id', 'status', 'frontEndId', 'matchDayOfWeek', 'matchNumber', 'matchDate', 'kickOffTime', 'sequence', 'homeTeam', 'awayTeam', 'tournament', 'results', 'poolInfo'])

In [21]:
with open("../../../data/sample_data/match_records_real_madrid_sample_20250124.json", "w") as f:
    f.write(json.dumps(match_records_list))

## 3. Test Query for Match Results

In [12]:
match_result = match_records_scraper.get_match_result_by_match_id(
    match_id="50068149",
)
match_result

TypeError: 'NoneType' object is not subscriptable

In [9]:
match_results = match_records_scraper.get_match_results_by_batch(
    match_id_list=["50039609", "50039827"],
)
len(match_results)

TypeError: 'NoneType' object is not subscriptable

In [9]:
match_results[1].keys()

dict_keys(['id', 'foPools', 'additionalResults'])

In [22]:
with open("../../../data/sample_data/match_results_sample_20250124.json", "w") as f:
    f.write(json.dumps(match_records_list))

In [16]:
s = "query lastOdds($matchId: String, $fbOddsTypes: [FBOddsType]!) {\n  matches: matchResult(matchId: $matchId) {\n    id\n    updateAt\n    statusUpdatedAt\n    foPools(fbOddsTypes: $fbOddsTypes, lastOdds: true) {\n      id\n      status\n      oddsType\n      instNo\n      inplay\n      name_ch\n      name_en\n      updateAt\n      lines(resultOnly: true) {\n        lineId\n        status\n        condition\n        combinations {\n          combId\n          str\n          status\n          currentOdds\n          selections {\n            selId\n            str\n            name_ch\n            name_en\n          }\n        }\n      }\n      closedLines {\n        lineId\n        status\n        condition\n        combinations {\n          combId\n          str\n          status\n          currentOdds\n          selections {\n            selId\n            str\n            name_ch\n            name_en\n          }\n        }\n      }\n    }\n  }\n}"
print(s)

query lastOdds($matchId: String, $fbOddsTypes: [FBOddsType]!) {
  matches: matchResult(matchId: $matchId) {
    id
    updateAt
    statusUpdatedAt
    foPools(fbOddsTypes: $fbOddsTypes, lastOdds: true) {
      id
      status
      oddsType
      instNo
      inplay
      name_ch
      name_en
      updateAt
      lines(resultOnly: true) {
        lineId
        status
        condition
        combinations {
          combId
          str
          status
          currentOdds
          selections {
            selId
            str
            name_ch
            name_en
          }
        }
      }
      closedLines {
        lineId
        status
        condition
        combinations {
          combId
          str
          status
          currentOdds
          selections {
            selId
            str
            name_ch
            name_en
          }
        }
      }
    }
  }
}

## 4. Test Query for Match Odds

In [13]:
match_odds = match_records_scraper.get_match_odds_by_batch(
    match_id_list=["50039609", "50039827"],
)
len(match_odds)

TypeError: 'NoneType' object is not subscriptable

In [11]:
match_odds[1].keys()

dict_keys(['id', 'updateAt', 'statusUpdatedAt', 'foPools'])

In [23]:
with open("../../../data/sample_data/match_odds_sample_20250124.json", "w") as f:
    f.write(json.dumps(match_records_list))

## 5. Test Query for Live Match Odds

In [12]:
live_match_odds_scraper = LiveMatchScraper()
live_match_odds = live_match_odds_scraper.get_live_matches_info_by_match_ids(
    match_id_list=None,
)

In [13]:
len(live_match_odds)

139

In [14]:
live_match_odds[0].keys()

dict_keys(['id', 'frontEndId', 'matchDate', 'kickOffTime', 'status', 'updateAt', 'sequence', 'esIndicatorEnabled', 'homeTeam', 'awayTeam', 'tournament', 'isInteractiveServiceAvailable', 'inplayDelay', 'venue', 'tvChannels', 'liveEvents', 'featureStartTime', 'featureMatchSequence', 'poolInfo', 'runningResult', 'runningResultExtra', 'adminOperation', 'foPools'])

In [14]:
for match in live_match_odds:
    print(f"{match['homeTeam']['name_ch']} v.s. {match['awayTeam']['name_ch']}")

艾雷恩 v.s. 艾杜哈尼
阿爾克馬爾 v.s. 羅馬
費倫巴治 v.s. 里昂
賀芬咸 v.s. 熱刺
波圖 v.s. 奧林比亞高斯
波杜基林特 v.s. 特拉維夫馬卡比
馬模 v.s. 川迪
卡拉巴克 v.s. 布加勒斯特星隊
柏辛域陀尼亞 v.s. 安德列治
皇家馬德里女足 v.s. 皇家蘇斯達女足
曼聯 v.s. 格拉斯哥流浪
拉素 v.s. 皇家蘇斯達
艾夫斯堡 v.s. 尼斯
法蘭克福 v.s. 費倫斯華路士
盧多格德斯 v.s. 米迪蘭特
PAOK v.s. 布拉格斯拉維亞
RFS v.s. 阿積士
聖基萊斯聯 v.s. 布拉加
域斯咸 v.s. 伯明翰
秘魯U20 v.s. 巴拉圭U20
諾羅斯特 v.s. 保地花高SP
聖貝拿度 v.s. 米拉索
葛度爾古斯 v.s. 羅沙里奧中央
堤格雷 v.s. 沙士菲
聖保羅 v.s. 古蘭尼
委內瑞拉U20 v.s. 智利U20
防衛者 v.s. 班菲特
紐維爾舊生 v.s. 利華達維亞獨立
拉魯斯 v.s. 萊斯查
墨爾本勝利女足 v.s. FC悉尼女足
墨爾本勝利 v.s. FC悉尼
艾沙瑪 v.s. 烏姆沙拉爾
艾華卡拉 v.s. 多哈艾阿拉比
格雷特霍夫 v.s. 凱沙羅頓
馬格德堡 v.s. 布倫瑞克
荷華高斯 v.s. 烏德勒支
迪加史卓普 v.s. 安曼
丹保殊 v.s. 奧斯
FC燕豪芬 v.s. 甘堡爾
洛達 v.s. 烏德勒支青年隊
維迪斯 v.s. 多德勒支
禾寧丹 v.s. 馬斯特里赫特
巴斯蒂亞 v.s. FC波城
卡昂 v.s. 甘岡
拉瓦勒 v.s. 特魯瓦
馬堤古斯 v.s. 艾米恩斯
梅斯 v.s. 格勒諾布爾
羅德茲 v.s. 阿些斯奧
禾夫斯堡 v.s. 基爾
艾爾切 v.s. 伊巴
拖連奴 v.s. 卡利亞里
歐塞爾 v.s. 聖伊天
聖圖爾登 v.s. 安特衛普
紐波特郡 v.s. 史雲頓
拉斯彭馬斯 v.s. 奧沙辛拿
錫菲聯 v.s. 侯城
巴拉卡斯中央 v.s. 競賽會
阿洛卡 v.s. 摩里倫斯
柏利斯天奴 v.s. 奧達斯
獨立隊 v.s. 沙米恩圖
貝格拉諾 v.s. 颶風隊
聖馬田聖祖安 v.s. 圖庫曼體育會
聖路易斯體育會 v.s. 尼卡沙
迪祖亞拿 v.s. 克雷塔羅
FC馬薩特蘭 v.s. 托盧卡
拉巴斯體育會 v.s. 哥雷卡米諾斯
威靈頓鳳凰 v.s. 中岸水手
紐卡素噴射機 v.s. 珀斯光輝
西悉尼流浪者女足 v.s. 墨爾本城女足
阿德萊德聯女足 v.s. 西部聯女足
FC麥克阿瑟 v.s. 墨爾本城
紐卡素噴射機女足 v.s. 坎培拉聯女足
史浩克04 v.s. 紐倫堡
科隆 v.s. 艾華斯堡
卡爾斯魯厄 v.s. 杜塞爾多夫
馬略卡 v.s. 貝迪斯
蒙彼利埃女足 v.s. 勒哈弗爾女足
科木 v.s. 阿特蘭大
多蒙特 v.s. 雲達不來梅
弗賴堡 v.s. 拜仁慕尼黑
RB萊比錫 v.s. 利華古遜
奧格斯堡 v.s. 海登咸
緬恩斯 v.s. 史特加
利物浦 v.s. 葉士域治
般尼茅夫 v.s. 諾定咸森林
白禮頓 v.s. 愛華頓
修咸頓 v.s. 紐卡素
狼隊 v.s. 阿仙奴
些路迪 v.s. 登地
鴨巴甸 v.s. 聖美倫
赫斯 v.s. 基爾馬諾克
羅斯郡 v.s. 喜伯年
聖莊士東 v.s. 馬瑟韋爾
馬德里體育會 v.s. 維拉利爾
法馬利卡奧 v.s. 艾馬多拉
法倫斯 v.s. 里奧艾維
泰斯達 v.s. 阿積士青年隊
摩納哥 v.s. 雷恩
拿玻里 v.s. 祖雲達斯
曼城 v.s. 車路士
西維爾 v.s. 愛斯賓奴
慕遜加柏 v.s. 波琴
燕豪芬 v.s. NAC
斯特拉斯堡 v.s. 里爾
AC卡薩比亞 v.s. 賓菲加
哈化柏林 v.s. 漢堡
安玻里 v.s. 博洛尼亞
華拉度列 v.s. 皇家馬德里
格羅寧根 v.s. 海倫芬
巴黎聖日耳門 v.s. 蘭斯
士砵亭 v.s. 國民隊
西悉尼流浪者 v.s. 奧克蘭FC
中岸水手女足 v.s. 威靈頓鳳凰女足
珀斯光輝女足 v.s. 布里斯班獅吼女足
幸運薛達 v.s. 施禾利
精英隊 v.s. 海牙
AC米蘭 v.s. 帕爾馬
登地聯 v.s. 格拉斯哥流浪
達斯泰特 v.s. 柏達邦
漢諾威 v.s. 普斯辛蒙斯達
烏爾姆 v.s. 雷根斯堡
華歷簡奴 v.s. 基羅納
華域克 v.s. 威廉二世
水晶宮 v.s. 賓福特
勒哈弗爾 v.s. 比斯特
艾斯杜尼 v.s. 甘馬雷斯
靴蒙特 v.s. 阿爾克馬爾青年隊
朗斯 v.s. 昂熱
圖盧茲 v.s. 蒙彼利埃
阿士東維拉 v.s. 韋斯咸
聖保利 v.s. 柏林聯
萊切 v.s. 國際米蘭
畢爾包 v.s. 雷加利斯
巴塞隆拿 v.s. 華倫西亞
威尼斯 v.s. 維羅納
燕豪芬青年隊 v.s. 芬洛
熱拿亞 v.s. 蒙沙
艾拉維斯 v.s. 切爾達
AVS v.s. 基維辛迪

In [24]:
with open("../../../data/sample_data/live_matches_sample_20250124.json", "w") as f:
    f.write(json.dumps(match_records_list))